#!/bin/bash -l

module load prod_util

if [ $# -ne 3 ] ; then
  now=$(date +"%Y%m%d")
  echo "You are trying to run the PETSS model but you missed something--"
  echo ""
  echo "Usage $0 <date ${now}> <cycle (00, 06, 12, 18)> <Skip P-ETSS model run (Y/N)"
  echo ""
  exit
fi

set -x

export PDY=$1
export cyc=$2
export jump=$3
export cycle=t${cyc}z

# Add some debugs...
set -xa


###############################################
#  Directory for MDL copy of com, pcom, tmp
###############################################

src=$(cd $(dirname $0)/.. && pwd)
root=${src}

export envir=prod
export HOMEpetss=${root}

export MDLTEST_DIR=${HOMEpetss}/dev/petss.v1.1.0
export COMROOT=${MDLTEST_DIR}/$envir/com
export COMIN=${MDLTEST_DIR}/$envir/com/petss/v1.2/petss.${PDY}

mkdir -p ${MDLTEST_DIR}
mkdir -p ${MDLTEST_DIR}/tmpnwprd1/
mkdir -p ${MDLTEST_DIR}/$envir/com/logs/

export job=petssImg_${PDY}_${cyc}
export outid="LL$job"
export jobid="${outid}.o${pid}"

export DATAROOT=${MDLTEST_DIR}/tmpnwprd1/
#export jlogfile=${COMROOT}/logs/jlogfile_Img.${PDY}.${cyc}

export RUN_ENVIR=MDLTEST
export KEEPDATA=NO

# Removing temp files generated by last time run

rm ${MDLTEST_DIR}/tmpnwprd1/png*.txt
rm ${MDLTEST_DIR}/tmpnwprd1/timing.txt

cd ${MDLTEST_DIR}/tmpnwprd1

setpdy.sh
. PDY


###############################################
# Kick off the LSF script
###############################################
${HOMEpetss}/dev/myEcf/jpetss_drawimages.ecf

############################################################

exit
############## END OF SCRIPT #######################
