50,15         T/B LAT'S    ET EAST COAST BASIN new 
W             WEST LONG    ET EAST COAST BASIN new  
87,52         L/R LON'S    ET EAST COAST BASIN new
FQUS23 KWNO 000000
GFS BASED STORM SURGE (IN TENTHS OF FT)    NOT VALID FOR TROPICAL STORMS
13
