80,45         T/B LAT'S    ET NEW ALASKA BERING BASIN (IMX=246)
W             WEST LONG    ET NEW ALASKA BERING BASIN
190,110       L/R LON'S    ET NEW ALASKA BERING BASIN (JMX=745)
FQAK23 KWNO 000000
GFS BASED STORM SURGE (IN TENTHS OF FT)    NOT VALID FOR TROPICAL STORMS
1
