45,10         T/B LAT'S    ET GULF COAST BASIN  
W             WEST LONG    ET GULF COAST BASIN   
105,70        L/R LON'S    ET GULF COAST BASIN  
FQGX23 KWNO 000000
GEFS BASED STORM TIDE  (IN TENTHS OF FT)    NOT VALID FOR TROPICAL STORMS
15
