#!/bin/sh

########################################
# Runs GFS MDL Extratropical Storm Surge Model
########################################

set -x
date
export PS4=' $SECONDS + '

#####################################
# SET SHELL PROCESSING VARIABLES
#####################################

export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
mkdir -p ${DATA}/out
cd $DATA

export LOCALJLOG="YES"
export jlogfile="${DATA}/jlogfile.${jobid:?}"

export pgmout="OUTPUT.${pid}"
export cycle=${cycle:-t${cyc}z}

export RUN_ENVIR=${RUN_ENVIR:-nco}
export NET=${NET:-petss}
export RUN=${RUN:-petss}
export EXECpetss=$HOMEpetss/exec
export SCRIPTSpetss=$HOMEpetss/scripts
export LOGSpetss=$HOMEpetss/logs
export PARMpetss=$HOMEpetss/parm
export USHpetss=$HOMEpetss/ush

export MP_CSS_INTERRUPT=yes
# Run setup to initialize working directory and utility scripts
setpdy.sh
. ./PDY

export DCOMbase=${DCOMbase:-${DCOMROOT:?}}
# bufrTank b255/xx102 diretory "DCOMbase1 (restricted access data)
export DCOMbase1=${DCOMbase1:-${DCOMROOT:?}}

export COMIN=${COMIN:-$(compath.py ${NET}/${petss_ver})}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${petss_ver}/${RUN}.${PDY})}
#export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}}
#export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

mkdir -p $COMOUT
env

# Call script
########################################################
# Execute the script.
########################################################
$SCRIPTSpetss/expetss_parsedat.sh
########################################################
export err=$?; err_chk

if [[ "${LOCALJLOG}" == "YES" ]]; then
  if [[ ! -r "${jlogfile}" ]]; then
    echo "Cannot read jlogfile (${jlogfile})"
  elif [[ ! -s "${jlogfile}" ]]; then
    echo "Jlogfile (${jlogfile}) is 0 bytes."
  else
    cp "${jlogfile}" "${COMOUT}"
  fi
fi

# Delete data dir
if [ "$KEEPDATA" != "YES" ]; then
  cd ${DATAROOT:?}
  rm -rf ${DATA}
fi

date
